#!/bin/sh

set -e

if [ "$BUILD" = "lint" ]; then
    flake8 tests
    isort -c -df -rc src tests
    black --check --diff src tests
elif [ "$BUILD" = "sdist" ]; then
    python3 setup.py sdist
    if [ -n "$TRAVIS_TAG" ]; then
        python3 -m twine upload --skip-existing dist/*
    fi
else
    coverage run setup.py test
    curl -s https://codecov.io/bash | bash
fi
