#!/bin/sh

set -e

if [ "$BUILD" = "lint" ]; then
    flake8 tests
    isort -c -df -rc src tests
    black --check --diff src tests
elif [ "$BUILD" = "sdist" ]; then
    python3 setup.py sdist
    if [ -n "$TRAVIS_TAG" ]; then
        twine upload --skip-existing dist/*
    fi
elif [ "$BUILD" = "wheel" ]; then
    cibuildwheel --output-dir wheelhouse
    if [ -n "$TRAVIS_TAG" ]; then
        twine upload --skip-existing wheelhouse/*
    fi
else
    python3 setup.py test
fi
