name: tests

on: [push, pull_request]

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install packages
        run: pip install black flake8 isort
      - name: Run linters
        run: |
          flake8 src tests
          isort -c -df -rc src tests
          black --check --diff src tests

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python: [3.8, 3.7, 3.6, pypy3]
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - name: Run tests
        run: |
          pip install -U pip setuptools wheel
          pip install .
          python -m unittest discover -v

  package:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Build package
        run: python setup.py sdist
      - name: Publish package
        if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/')
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}

  wheel:
    runs-on: ${{ matrix.os }}
    needs: [lint, test]
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Build wheels
        env:
          CI: true
          CIBW_SKIP: cp27-* cp33-* cp34-*
          CIBW_TEST_COMMAND: python -m unittest discover -s {project}/tests
        run: |
          pip install cibuildwheel
          cibuildwheel --output-dir dist
      - name: Publish wheels
        if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/')
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
